### ISSUE TITLE
The zip of origin video data has broken. Is there other download path？ 

### ISSUE THREAD

**Issue by sdjhshbswp** [bcmi/Causal-VidQA#10]

**Comment by Jiangtong-Li** [comment]
I don't understand what do your mean by 'broken'? 
To my best knowledge, the original video data can be download and unzipped.

**Comment by sdjhshbswp** [comment]
> 

Sorry for not expressing it clearly last time. I noticed that a certain number of answers of the same video in 'QA.zip'  are all -1, but the answer number are between 0-4 in the other question-answer pairs.

**Comment by Jiangtong-Li** [comment]
﻿-1 indicate the test QA，we haven't release this part of answers to prevent someone adjust hyper-parameter on test set.You can evaluate the test set in CodaLab.Best wishes！Jiangtong Li在 2023年6月22日，23:01，sdjhshbswp ***@***.***> 写道：﻿


Sorry for not expressing it clearly last time. I noticed that a certain number of answers of the same video in 'QA.zip'  are all -1, but the answer number are between 0-4 in the other question-answer pairs.
