### ISSUE TITLE
test set evaluation

### ISSUE THREAD

**Issue by XLiu443** [bcmi/Causal-VidQA#11]
Thanks for this great work. It seems there are some issues when submitting results on the CodaLab for test set evaluation. It always indicates "submitting" without any outputs. Could you provide any help?
![causal_submission1](https://github.com/bcmi/Causal-VidQA/assets/26985786/9c9edc3c-b6ab-4ed8-bc48-fd9a2580fa14)

**Comment by Jiangtong-Li** [comment]
As we have stated in submission format, you should directly zip the answer.json without placing it into another folder.
Hope it can help you.
If you have any other problem, please let me know.
