### ISSUE TITLE
How much RAM is needed for using BERT features?

### ISSUE THREAD

**Issue by JackyWang2001** [bcmi/Causal-VidQA#2]
Thanks for your innovative work.
I am trying to run the code with the BERT features. However, I failed to `python dataset/load.py` because of a `Bus error`. In my knowledge, this is probably because I don't have enough RAM for creating the shared array. After this error, I saw that the used shared memory was around 60G. Would you let me know how much RAM is needed for using BERT features? If the usage is large, are there any alternative approaches?
Thank you!

**Comment by LemonQC** [comment]
I also found there may some errors while loading the feature.

**Comment by Jiangtong-Li** [comment]
When I train these model with BERT feature, the memory of my server is 512G. If your server do not have enough memory, you don’t need to load the whole BERT feature to the memory, you can open the h5 file, and read the corresponding feature during training.
