### ISSUE TITLE
Raw videos have bounding boxes and masks embedded

### ISSUE THREAD

**Issue by ahmadmobeen** [bcmi/Causal-VidQA#4]
![image](https://user-images.githubusercontent.com/15436661/190989717-a6222f5a-ac41-4d0e-84f3-b1de631189f5.png)
Downloaded from here https://cloud.bcmi.sjtu.edu.cn/sharing/FYDmyDwff

**Comment by Jiangtong-Li** [comment]
Since our video are all from k-700 video action recognization dataset, you can download the k-700 dataset and search the video with the video id provided in our three split.pkl file.
