### ISSUE TITLE
Can you release the results of the valid datasets.

### ISSUE THREAD

**Issue by LemonQC** [bcmi/Causal-VidQA#5]
One can only submit 10 times for the datasets, which extremely hinders the utilization of the data. And hope you can release your test data.

**Comment by LemonQC** [comment]
Moreover, can you provide a script for transferring the results  to the submission format

**Comment by Jiangtong-Li** [comment]
The benchmark results on validation dataset will be released recently.

As for the code to convert the these two format, it is quite easy.  I will update the convert script recently.
If you are in hurry, you can follow the rules to convert.
The convert rule is listed as follow: 
_0 indicate descriptive 
_1 indicate explanatory
_2 indicate predictive-answer
_3 indicate predictive-reason
_4 indicate counterfactual-answer
_5 indicate counterfactual-reason

**Comment by LemonQC** [comment]
Does this right?


import json
data=json.load(open('result/B2A/B2A_glove_test.json','r'))
collect={}
for key,val in data.items():
    index_key=key[-1]
    s_key=key[:-2]
    if s_key not in collect:
        collect[s_key]={
            "descriptive": {"answer": -1}, 
            "explanatory": {"answer": -1}, 
            "predictive": {"answer": -1, "reason": -1}, 
            "counterfactual": {"answer": -1, "reason": -1}            
        }
    
    val=val['prediction']
    if index_key=='0':
        collect[s_key]['descriptive']['answer']=int(val)
    elif index_key=='1':
        collect[s_key]['explanatory']['answer']=int(val)
    elif index_key=='2':
        collect[s_key]['predictive']['answer']=int(val)
    elif index_key=='3':
        collect[s_key]['predictive']['reason']=int(val)
    elif index_key=='4':
        collect[s_key]['counterfactual']['answer']=int(val)
    elif index_key=='5':
        collect[s_key]['counterfactual']['reason']=int(val)
    else:
        print('异常')
with open('answer.json','w') as f:
    f.write(json.dumps(collect,indent=4))

**Comment by Jiangtong-Li** [comment]
That is right～

**Comment by LemonQC** [comment]
Many Thanks. I will try the model and follow your work. Best wishes.
