### ISSUE TITLE
The results can not be reproduced.

### ISSUE THREAD

**Issue by LemonQC** [bcmi/Causal-VidQA#6]
I utilize the source code without any modification. However, I can not obtain the results which are significantly lower.
![image](https://user-images.githubusercontent.com/30914380/191641801-a619dcb0-ddca-4d2f-bea0-e07672ee55a7.png)
![image](https://user-images.githubusercontent.com/30914380/191641858-b030e3b5-09d1-4ca9-a78e-035f65cda5ee.png)

**Comment by Jiangtong-Li** [comment]
Try larger hidden size.
