### ISSUE TITLE
Can you show more details about your features?

### ISSUE THREAD

**Issue by LemonQC** [bcmi/Causal-VidQA#7]
Such as , bert_adj.pkl, what's the adj and the text length is？

**Comment by Jiangtong-Li** [comment]
As you know, the B2A use the semantic structure of text to bridge the question feature with the video feature. The adj is indeed the semantic structure of the question or answer, and the text length is the corresponding length of the question and answer, for more details about adj, please refer to the original paper of B2A and the definition of dependency parsing.

Hint, the author of B2A did not release their code by the time submission deadline of CVPR2021, therefore the code for B2A is reproduce by ourselves. If you have more problems about B2A, you can also discuss with the authors of B2A.

**Comment by LemonQC** [comment]
Does this mean that my own model does not need to load this file?

**Comment by Jiangtong-Li** [comment]
Yes！Only the B2A need this file。

**Comment by Jiangtong-Li** [comment]
If you have problem, you may directly contact with me by e-mail. I may not check this repo everyday.

**Comment by LemonQC** [comment]
Ok, many thanks.
