### ISSUE TITLE
Where is dataset_answer.tar?

### ISSUE THREAD

**Issue by wonzin** [bcmi/Causal-VidQA#8]
dataset.md 

* dataset_answer.tar: This is the ground truth answer index for all the answers and reasons.

However, I cannot find the dataset_answer.tar in here(https://cloud.bcmi.sjtu.edu.cn/fsdownload/FYDmyDwff/CausalQA).

**Comment by Jiangtong-Li** [comment]
please refer to #Download 4. text annotation
