### ISSUE TITLE
Data unavailable

### ISSUE THREAD

**Issue by vcyrot** [bcmi/Causal-VidQA#9]
Hi! 
I have been trying to reproduce your results but have faced some issues when downloading the data. 
When I click on the links you provided, I am asked to use a school VPN:

"抱歉，如果您是在校外访问本网站。

建议您先拨通学校的VPN后再访问。

关于VPN，请参考：[交大VPN](https://net.sjtu.edu.cn/wlfw/VPN.htm)"

Therefore it seems like I cannot access the data... 
Could you perhaps help me with that problem?

Thank you

**Comment by Jiangtong-Li** [comment]
Due to some political reasons, all resource about sjtu cannot be accessed recently. You can try next week.
